---

  - name: Ensure SABnzbd service group is present
    group:
      name: "{{ sabnzbd_group_name }}"
      gid: "{{ sabnzbd_group_gid }}"
      system: true
      state: present
           
  - name: Ensure SABnzbd service user is present
    user:
      name: "{{ sabnzbd_user_name }}"
      uid: "{{ sabnzbd_user_uid }}"
      group: "{{ sabnzbd_group_name }}"
      home: "{{ sabnzbd_user_home }}"
      system: true
      state: present

  - name: Ensure SABnzbd dependencies are installed
    package:
      name: "{{ sabnzbd_dependencies }}"
      state: present

  - name: Ensure SAByenc is installed
    pip:
      name: sabyenc
      state: present

  - name: Fetch UnRAR source from RARLAB
    get_url:
      url: http://rarlab.com/rar/unrarsrc-5.2.7.tar.gz
      dest: /root/
      sha256sum: ef14757e943787b439fedf2c564c1f38d0db315528a928e0de170860717e2fac

  - name: Ensure UnRAR source has been unarchived
    unarchive:
      src: /root/unrarsrc-5.2.7.tar.gz
      dest: /root/
      copy: false

  - name: Ensure UnRAR has been built
    shell: make -f makefile
    args:
      chdir: /root/unrar
      creates: /root/unrar/unrar

  - name: Ensure UnRAR has been installed
    shell: make -f makefile install
    args:
      chdir: /root/unrar
      creates: /usr/bin/unrar

  - name: Ensure SABnzbd source directory exists
    file:
      dest: "{{ sabnzbd_user_home }}/src"
      owner: "{{ sabnzbd_user_name }}"
      group: "{{ sabnzbd_group_name }}"
      recurse: true
      state: directory

  - name: Ensure SABnzbd library directory exists
    file:
      dest: "{{ sabnzbd_library_path }}"
      owner: "{{ sabnzbd_user_name }}"
      group: "{{ sabnzbd_group_name }}"
      state: directory

  - name: Fetch SABnzbd source code
    git:
      repo: "{{ sabnzbd_clone_uri }}"
      dest: "{{ sabnzbd_user_home }}/src"
      update: "{{ sabnzbd_follow_git }}"
    notify: Restart SABnzbd service
    become: true
    become_user: "{{ sabnzbd_user_name }}"

  - name: Deploy SABnzbd service manifest
    template:
      dest: "{{ sabnzbd_service_file.dest }}"
      src: "{{ sabnzbd_service_file.src }}"
      owner: root
      group: root
      mode: 0600
    notify:
      - Reload SABnzbd service config
      - Restart SABnzbd service

  - meta: flush_handlers

  - name: Ensure SABnzbd service is running
    service:
      name: sabnzbd
      state: started
    when: not sabnzbd_packer_provision

  - name: Ensure SABnzbd service is enabled on boot
    service:
      name: sabnzbd
      enabled: true
